[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/",
]
# 禁用编译器警告
solc = "0.8.33"
via_ir = true
optimizer = true
optimizer_runs = 1000000  # 更高的 runs 值可以减少合约大小
ignored_error_codes = [2018, 2519, 5667, 2072, 3860, 5574, 2424]

# Linter 配置 - 忽略特定规则
[lint]
exclude_lints = ["mixed-case-variable", "mixed-case-function", "unsafe-typecast"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
